version: "3.9"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    restart: always

  elasticsearch:
    image: elasticsearch:7.6.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.data=/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  chesshub:
    build:
      context: ./chesshub
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - elasticsearch
    restart: always

volumes:
  esdata:
    driver: local
