version: "3.9" 

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    restart: always

  chesshub:
    build: ./chesshub 
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/chesshub
    depends_on:
      - mongo
    restart: always